services:
  traefik:
    image: traefik:v3.6.7
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--experimental.plugins.lowercase.modulename=github.com/trinnylondon/lowercase"
      - "--experimental.plugins.lowercase.version=v0.1.3"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"


#  middlewares:
#      my-lowercase:
#          plugin:
#              lowercase:
#                  unused: var

  httpd:
    build: httpd
    labels:
      - "traefik.http.routers.httpd.rule=Host(`httpd.localhost`)"
#      - "traefik.http.middlewares.test-replacepathregex.replacepathregex.regex=^/foo/(.*)"
#      - "traefik.http.middlewares.test-replacepathregex.replacepathregex.replacement=/bar/$$1"
      # - /([A-Z]+)/g \L$1

  lighttpd:
    build: lighttpd
    labels:
      - "traefik.http.routers.lighttpd.rule=Host(`lighttpd.localhost`)"
#
#  nginx-test:
#    build:
#      context: httpd
#      dockerfile: httpd/Dockerfiledown lighttpd

#    ports:
#      - "8080:80"
