services:
  traefik:
    image: traefik:v3.6.7
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"

  httpd:
    build: httpd
    labels:
      - "traefik.http.routers.httpd.rule=Host(`httpd.localhost`)"

  lighttpd:
    build: lighttpd
    labels:
      - "traefik.http.routers.lighttpd.rule=Host(`lighttpd.localhost`)"
#
#  nginx-test:
#    build:
#      context: httpd
#      dockerfile: httpd/Dockerfiledown lighttpd

#    ports:
#      - "8080:80"
