#
# This configuration file allows the manual to be accessed at 
# http://localhost/manual/
#
Alias /manual /usr/local/apache2/manual

<Directory "/usr/local/apache2/manual">
    Options Indexes
    AllowOverride None
    Require all granted

    RedirectMatch 301 ^/manual/(?:da|de|en|es|fr|ja|ko|pt-br|ru|tr|zh-cn)(/.*)$ "/manual$1"
</Directory>
