FROM httpd:2.4.66-alpine
COPY conf/httpd.conf /usr/local/apache2/conf/
COPY conf.d/ /usr/local/apache2/conf.d/
COPY manual/ /usr/local/apache2/manual/

#COPY lorem-ipsum/ /usr/local/apache2/htdocs/
#COPY static/ /usr/local/apache2/htdocs/static/
#COPY themes/ /usr/local/apache2/htdocs/themes/
